replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: jc21/nginx-proxy-manager
  tag: 2.11.1
  pullPolicy: IfNotPresent
services:
  - name: http
    port: 80
    targetPort: "80"
    protocol: TCP
  - name: https
    port: 443
    targetPort: "443"
    protocol: TCP
  - name: admin
    port: 81
    targetPort: "81"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  env1:
    name: DB_MYSQL_HOST
    value: mysql
  env2:
    name: DB_MYSQL_PORT
    value: "3306"
  env3:
    name: DB_MYSQL_USER
    value: npm
  env4:
    name: DB_MYSQL_PASSWORD
    value: ""
  env5:
    name: DB_MYSQL_NAME
    value: npm
