replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: "passivelemon/terraria-docker"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7777

resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1024Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "local"

env:
  env1:
    name: WORLDNAME
    value: "World"
  env2:
    name: MAXPLAYERS
    value: "8"
  env3:
    name: AUTOCREATE
    value: "2"
  env4:
    name: PORT
    value: "7777"
  env5:
    name: DIFFICULTY
    value: "0"
  env6:
    name: SECURE
    value: "1"