replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: syncthing/syncthing
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: webui
    port: 8384
    targetPort: "8384"
    protocol: TCP
  - name: datasync
    port: 22000
    targetPort: "22000"
    protocol: TCP
  - name: discovery
    port: 21027
    targetPort: "21027"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  env1:
    name: STGUIADDRESS
    value: 0.0.0.0:8384
  env2:
    name: STNOUPGRADE
    value: "true"
