replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: teamspeak
  tag: "3.13.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: voice
      port: 9987
      protocol: UDP
    - name: query  
      port: 10011
      protocol: TCP
    - name: filetransfer
      port: 30033
      protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m 
    memory: 512Mi

persistence:  
  enabled: true
  size: 5Gi
  storageClass: "local"

env:
  env1:
    name: TS3SERVER_DB_PLUGIN
    value: "ts3db_mysql"
  env2:
    name: TS3SERVER_DB_SQLCREATEPATH 
    value: "create_mysql"
  env3:
    name: TS3SERVER_DB_WAITUNTILREADY
    value: "30"
  env4:
    name: TS3SERVER_LICENSE
    value: "accept"
  env5:  
    name: TS3SERVER_DB_HOST
    value: "localhost"
  env6:
    name: TS3SERVER_DB_NAME
    value: "teamspeak"
  env7:
    name: TS3SERVER_DB_PORT
    value: "3306"
  env8:
    name: TS3SERVER_DB_USER
    value: "root"
  env9:
    name: TS3SERVER_DB_PASSWORD
    value: "password"