apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-proxy-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-proxy-manager.labels" . | nindent 8 }}
        {{- include "nginx-proxy-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "nginx-proxy-manager.name" . }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.services }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          env:
            {{- if kindIs "array" .Values.env }}
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            {{- else if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ $value.name }}"
              value: "{{ $value.value }}"
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: nginx-proxy-manager-data
              
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: nginx-proxy-manager-data
          persistentVolumeClaim:
            claimName: {{ include "nginx-proxy-manager.fullname" . }}-pvc
      {{- end }}