apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kasm-kali.fullname" . }}-pvc
  labels:
    {{- include "kasm-kali.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}