apiVersion: v1
kind: Service
metadata:
  name: {{ include "kasm-kali.fullname" . }}
  labels:
    {{- include "kasm-kali.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6901
      protocol: TCP
      name: vnc
  selector:
    {{- include "kasm-kali.selectorLabels" . | nindent 4 }}