apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ include "terraria.fullname" . }}-data
 labels:
   {{- include "terraria.labels" . | nindent 4 }}
spec:
 accessModes:
   - {{ .Values.persistence.accessMode }}
 resources:
   requests:
     storage: {{ .Values.persistence.size }}
 storageClassName: {{ .Values.persistence.storageClass | quote }}