replicaCount: 1

image:
  imageRegistry: registry-2.yunna.net
  repository: dyrnq/open-webui
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      externalPort: 8080
      protocol: TCP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

env:
  env1:
    name: OLLAMA_BASE_URL
    value: "your_ollama_base_url"
  env2:
    name: WEBUI_SECRET_KEY  
    value: "your_webui_secret_key"