replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: louislam/uptime-kuma
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local"

env:
  env1:
    name: NODE_ENV
    value: production
  env2:
    name: KUMA_DEBUG
    value: "false"
