apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-wechat.fullname" . }}
  labels:
    {{- include "docker-wechat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-wechat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docker-wechat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 5800
            - name: vnc
              containerPort: 5900
          env:
            {{- if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: docker-wechat-storage
              mountPath: /root
            - name: dev-snd
              mountPath: /dev/snd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: docker-wechat-storage
          persistentVolumeClaim:
            claimName: {{ include "docker-wechat.fullname" . }}-pvc
        - name: dev-snd
          hostPath:
            path: /dev/snd