apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-wechat.fullname" . }}-pvc
  labels:
    {{- include "docker-wechat.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}