replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: kasmweb/kali-rolling-desktop
  tag: "1.16.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6901

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
    shm-size: 512Mi
  requests:
    cpu: 1000m
    memory: 2Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

env:
  env1:
    name: VNC_PW
    value: "password"