replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: discourse
  tag: "3.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

env:
  env1:
    name: DISCOURSE_DB_HOST
    value: "postgresql"
  env2:
    name: DISCOURSE_DB_NAME
    value: "discourse"
  env3:
    name: DISCOURSE_DB_USERNAME
    value: "discourse"
  env4:
    name: DISCOURSE_DB_PASSWORD
    value: "discourse123"
  env5:
    name: DISCOURSE_REDIS_HOST  
    value: "redis"
  env6:
    name: DISCOURSE_REDIS_PORT
    value: "6379"