apiVersion: v1
kind: Service
metadata:
  name: {{ include "gameserver.fullname" . }}
  labels:
    {{- include "gameserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "gameserver.selectorLabels" . | nindent 4 }} 