apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gameserver.fullname" . }}
  labels:
    {{- include "gameserver.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "gameserver.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gameserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gameserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "gameserver.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.interactiveTerminal.enabled }}
          stdin: true
          tty: true
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
            {{- range .Values.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: game-data
              mountPath: {{ .Values.persistence.gameData.mountPath }}
            - name: game-file
              mountPath: {{ .Values.persistence.gameFile.mountPath }}
            - name: game-file
              mountPath: /home/steam/.local
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: game-data
          persistentVolumeClaim:
            claimName: {{ include "gameserver.fullname" . }}-game-data
        - name: game-file
          persistentVolumeClaim:
            claimName: {{ include "gameserver.fullname" . }}-game-file
      {{- end }} 