apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oracle.fullname" . }}-pvc
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}