apiVersion: v2
name: nacos
description: 阿里巴巴开源的服务发现和配置管理平台
version: 1.0.0
appVersion: v2.3.0
home: https://nacos.io/
sources:
  - https://github.com/alibaba/nacos
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: microservices
  yunna.net/category-zh: 微服务
keywords:
  - Service-Discovery
  - Configuration-Management
  - Microservices
icon: https://assets.yunna.net/i/2024/12/22/3x5aey.png
