replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: nacos/nacos-server
  tag: v2.3.0
  pullPolicy: IfNotPresent
services:
  - name: http
    port: 8848
    targetPort: "8848"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local

env:
  env1:
    name: MODE
    value: standalone
  env2:
    name: SPRING_DATASOURCE_PLATFORM
    value: mysql
  env3:
    name: MYSQL_SERVICE_HOST
    value: mysql
