apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatgpt-next-web.fullname" . }}
  labels:
    {{- include "chatgpt-next-web.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.env.env1.value | b64enc }}
  secret-key: {{ .Values.env.env2.value | b64enc }}