apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}-pvc
  labels:
    app: {{ include "minecraft-bedrock.name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }} 