apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}
  labels:
    app: {{ include "minecraft-bedrock.name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ include "minecraft-bedrock.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "minecraft-bedrock.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "minecraft-bedrock.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bedrock
              containerPort: 19132
              protocol: UDP
          env:
            {{- if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: bedrock
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: bedrock
            initialDelaySeconds: 15
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: bedrock
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "minecraft-bedrock.fullname" . }}-pvc 