apiVersion: v1
kind: Service
metadata:
 name: {{ include "syncthing.fullname" . }}
 labels:
   {{- include "syncthing.labels" . | nindent 4 }}
spec:
 type: ClusterIP
 ports:
   {{- range .Values.services }}
   - name: {{ .name }}
     port: {{ .port }}
     targetPort: {{ .targetPort }}
     protocol: {{ .protocol }}
   {{- end }}
 selector:
   {{- include "syncthing.selectorLabels" . | nindent 4 }}